-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  strava_activity_id bigint NOT NULL,
  name text NOT NULL,
  sport_type text NOT NULL,
  start_date timestamp with time zone NOT NULL,
  start_date_local timestamp with time zone NOT NULL,
  timezone text,
  distance numeric,
  moving_time integer,
  elapsed_time integer,
  total_elevation_gain numeric,
  average_speed numeric,
  max_speed numeric,
  average_heartrate integer,
  max_heartrate integer,
  has_heartrate boolean DEFAULT false,
  average_watts integer,
  max_watts integer,
  weighted_average_watts integer,
  kilojoules numeric,
  has_power boolean DEFAULT false,
  trainer boolean DEFAULT false,
  commute boolean DEFAULT false,
  manual boolean DEFAULT false,
  achievement_count integer DEFAULT 0,
  kudos_count integer DEFAULT 0,
  comment_count integer DEFAULT 0,
  week_number integer,
  month_number integer,
  year_number integer,
  day_of_week integer,
  average_pace numeric,
  elevation_per_km numeric,
  efficiency_score numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  relative_effort integer,
  perceived_exertion integer,
  training_load_score double precision,
  intensity_score double precision,
  recovery_time integer,
  normalized_power double precision,
  training_stress_score double precision,
  power_zones jsonb,
  heart_rate_zones jsonb,
  pace_zones jsonb,
  CONSTRAINT activities_pkey PRIMARY KEY (id),
  CONSTRAINT activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.goal_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_goal_id uuid NOT NULL,
  activity_id character varying,
  activity_date date NOT NULL,
  value_achieved numeric,
  contribution_amount numeric,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT goal_progress_pkey PRIMARY KEY (id),
  CONSTRAINT goal_progress_user_goal_id_fkey FOREIGN KEY (user_goal_id) REFERENCES public.user_goals(id)
);
CREATE TABLE public.goal_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  display_name character varying NOT NULL,
  description text NOT NULL,
  category character varying NOT NULL,
  metric_type character varying NOT NULL,
  unit character varying,
  target_guidance text,
  calculation_method text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT goal_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.strava_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  token_type character varying DEFAULT 'Bearer'::character varying,
  expires_at timestamp with time zone NOT NULL,
  expires_in integer NOT NULL,
  strava_athlete_id bigint NOT NULL,
  athlete_firstname character varying,
  athlete_lastname character varying,
  athlete_profile text,
  scope text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT strava_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT strava_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.sync_state (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  last_activity_sync timestamp with time zone,
  last_full_sync timestamp with time zone,
  earliest_activity_date date,
  latest_activity_date date,
  total_activities_synced integer DEFAULT 0,
  full_sync_completed boolean DEFAULT false,
  sync_enabled boolean DEFAULT true,
  sync_requests_today integer DEFAULT 0,
  last_sync_date date DEFAULT CURRENT_DATE,
  consecutive_errors integer DEFAULT 0,
  last_error_message text,
  last_error_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_sync_error jsonb,
  CONSTRAINT sync_state_pkey PRIMARY KEY (id),
  CONSTRAINT sync_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_goals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  goal_type_id uuid NOT NULL,
  target_value numeric,
  target_unit character varying,
  target_date date,
  time_period character varying DEFAULT 'weekly'::character varying,
  current_progress numeric DEFAULT 0,
  best_result numeric,
  streak_count integer DEFAULT 0,
  goal_data jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  is_completed boolean DEFAULT false,
  priority integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  last_progress_update timestamp with time zone,
  CONSTRAINT user_goals_pkey PRIMARY KEY (id),
  CONSTRAINT user_goals_goal_type_id_fkey FOREIGN KEY (goal_type_id) REFERENCES public.goal_types(id)
);
CREATE TABLE public.user_onboarding (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  goals_completed boolean DEFAULT false,
  strava_connected boolean DEFAULT false,
  current_step character varying DEFAULT 'goals'::character varying,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_onboarding_pkey PRIMARY KEY (id)
);
CREATE TABLE public.weekly_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  week_start_date date NOT NULL,
  year_number integer NOT NULL,
  week_number integer NOT NULL,
  total_distance numeric DEFAULT 0,
  total_moving_time integer DEFAULT 0,
  total_elevation_gain numeric DEFAULT 0,
  activity_count integer DEFAULT 0,
  run_distance numeric DEFAULT 0,
  run_time integer DEFAULT 0,
  run_count integer DEFAULT 0,
  bike_distance numeric DEFAULT 0,
  bike_time integer DEFAULT 0,
  bike_count integer DEFAULT 0,
  swim_distance numeric DEFAULT 0,
  swim_time integer DEFAULT 0,
  swim_count integer DEFAULT 0,
  other_time integer DEFAULT 0,
  other_count integer DEFAULT 0,
  avg_heartrate numeric,
  avg_power integer,
  avg_pace numeric,
  longest_distance numeric,
  fastest_pace numeric,
  highest_power integer,
  activities_with_hr integer DEFAULT 0,
  activities_with_power integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT weekly_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT weekly_metrics_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);